version: "3.8"

services:
  orthanc:
    image: orthancteam/orthanc:latest-full
    restart: unless-stopped
    ports:
      - "8042:8042"
      - "4242:4242"
      - "104:104"
    environment:
      ORTHANC__REGISTERED_USERS: "{}"
      VERBOSE_STARTUP: "true"
      SERVE_FOLDERS_PLUGIN_ENABLED: "true"
      TRANSFERS_PLUGIN_ENABLED: "true"
      ORTHANC_WEB_VIEWER_PLUGIN_ENABLED: "true"
      OSIMIS_WEB_VIEWER1_ALPHA_PLUGIN_ENABLED: "true"
      VOLVIEW_PLUGIN_ENABLED: "true"
      OHIF_PLUGIN_ENABLED: "true"
      MPPS_SCP_PLUGIN_ENABLED: "true"
      MPPS_SCP_AE_TITLE: "PACS_SERVER"
      MPPS_SCP_PORT: "4242"
      ORTHANC_DB_HOST: "postgresql"
      ORTHANC_DB_USER: "orthanc"
      ORTHANC_DB_PASSWORD: "orthanc_password"
      ORTHANC_DB_NAME: "orthanc"
      DICOM_WEB_PLUGIN_ENABLED: '{"DicomWeb": true, "Enable": true}'
      ORTHANC_EXPLORER_2_ENABLED: '{"Enable": true, "IsDefaultOrthancUI": false}'
      MODALITY_WORKLISTS_PLUGIN_ENABLED: "true"
      MODALITY_WORKLISTS_DIRECTORY: "/worklists"
      ORTHANC__Verbose: "true"
    volumes:
      - ./orthanc-data:/var/lib/orthanc/db
      - ./orthanc.json:/etc/orthanc/orthanc.json
      - ./worklists:/worklists
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - dicom-network

  postgresql:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: orthanc
      POSTGRES_PASSWORD: orthanc_password
      POSTGRES_DB: orthanc
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orthanc -d orthanc"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dicom-network

  pgweb:
    image: sosedoff/pgweb
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      PGWEB_DATABASE_URL: "postgres://orthanc:orthanc_password@postgresql:5432/orthanc?sslmode=disable"
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - dicom-network

  backup:
    image: postgres:14
    restart: "no"
    environment:
      PGPASSWORD: orthanc_password
    volumes:
      - ./backups:/backups
      - ./scripts:/scripts
    networks:
      - dicom-network
    profiles:
      - backup

networks:
  dicom-network:
    driver: bridge

volumes:
  orthanc-data:
  postgresql_data:
